name: 🔒 Check PR Source Branch to master

on:
  pull_request:
    branches:
      - master  # Triggered when a PR is created/updated targeting the master branch

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check if PR source branch is dev'
        # If the PR source branch name (github.head_ref) is not 'dev'
        if: github.head_ref != 'dev'
        run: |
          echo "Error: Merges to the master branch are only allowed from the dev branch."
          echo "This PR is from the ${{ github.head_ref }} branch."
          exit 1 # Exit with error code 1 to mark this job as "failed"
      
      - name: 'Check if version label exists'
        # Check if PR has one of the required labels: major, minor, or patch
        run: |
          labels=$(jq -r '.pull_request.labels[].name' <<< '${{ toJson(github.event) }}')
          echo "PR labels: $labels"
          
          if echo "$labels" | grep -qiE "^(major|minor|patch)$"; then
            echo "OK: Version label found."
          else
            echo "Error: PR must have a version label (major, minor, or patch)."
            exit 1
          fi
      
      - name: 'Check OK'
        # If the PR source branch name is 'dev'
        if: github.head_ref == 'dev'
        run: |
          echo "OK: This PR is from the dev branch."
